markdown: kramdown
permalink: /:title/
url: http://yourbay.me
name: Hyongbai(Ram Han)
author: Hyongbai(Ram Han)
email: hyongbai@gmail.com
duoshuo: yourbay
#beian: 沪ICP备07500366号
baidu: 3234957
weibo: 1854281601
github: hyongbai
safe: true
paginate: 20
about: "Why so serious! any@hyongbai"
