# Site settings
title: yourbay.me
email: hyongbai@q-supereme.com
description: 'Copyright © @hyongbai'
url: "http://yourbay.me" # the base hostname & protocol for your site
twitter_username: hyongbai
github_username:  hyongbai

markdown_ext:  markdown,mkd,mkdn,md
permalink: /:categories/:year/:month/:day/:title/
name: Hyongbai(Ram Han)
author: Hyongbai(Ram Han)
email: hyongbai@gmail.com
duoshuo: yourbay
baidu: 3234957
weibo: 1854281601
github: hyongbai
safe: true
paginate: 20

# Build settings
sass:
  sass_dir: _sass
  style: :compressed
gems: 
  - jekyll-paginate
# markdown: redcarpet # [ maruku | rdiscount | kramdown | redcarpet ]
# redcarpet:
#     extensions: ["tables"]
highlighter: rouge
