markdown: rdiscount
permalink: /:title/
url: http://yourbay.me
name: Hyongbai(Ram Han)
author: Hyongbai(Ram Han)
email: hyongbai@gmail.com
duoshuo: alensw
beian: 沪ICP备07500366号
baidu: 3234957
weibo: 1489508705
github: hyongbai
pygments: true
safe: true
paginate: 20
about: "Hello World! Why so serious"
