markdown: rdiscount
permalink: /:title/
url: http://alensw.com
name: Alen Software
author: Alen
email: nanling.z@gmail.com
duoshuo: alensw
beian: 沪ICP备07500366号
baidu: 3234957
weibo: 1489508705
github: neithern
pygments: true
safe: true
paginate: 20
about: "这里是作者南岭的个人博客。主要用于自己开发的一些软件作品。。。"
