# Site settings
title: yourbay.me
email: hyongbai@q-supereme.com
description: 'Copyright © @hyongbai'
url: "http://yourbay.me" # the base hostname & protocol for your site
twitter_username: hyongbai
github_username:  hyongbai

# Build settings
markdown: kramdown
markdown_ext:  markdown,mkd,mkdn,md
permalink: /:title/
baseurl: http://yourbay.me
name: Hyongbai(Ram Han)
author: Hyongbai(Ram Han)
email: hyongbai@gmail.com
duoshuo: yourbay
baidu: 3234957
weibo: 1854281601
github: hyongbai
safe: true
paginate: 20
